In [110]:
import pandas as pd
import numpy as np

df=pd.read_csv("social_anxiety_dataset.csv")

df.shape
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target', 'is_Anxious',
       'Therapy History'],
      dtype='str')

In [111]:
df.shape

(2030, 22)

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1968 non-null   float64
 1   Gender                             1911 non-null   str
 2   Occupation                         2030 non-null   str
 3   Sleep Hours                        1994 non-null   float64
 4   Physical Activity (hrs/week)       2030 non-null   float64
 5   Caffeine Intake (mg/day)           1936 non-null   float64
 6   Alcohol Consumption (drinks/week)  2030 non-null   int64
 7   Smoking                            1924 non-null   str
 8   Family History of Anxiety          2030 non-null   str
 9   Stress Level (1-10)                2030 non-null   int64
 10  Heart Rate (bpm)                   2030 non-null   int64
 11  Breathing Rate (breaths/min)       2030 non-null   int64
 12  Sweating Level (1-5)               2030 non-null   int64
 13  Dizziness                          2030 non-null   str
 14  Medication                         1921 non-null   str
 15  Therapy Sessions (per month)       2030 non-null   int64
 16  Recent Major Life Event            2030 non-null   str
 17  Diet Quality (1-10)                1952 non-null   float64
 18  Anxiety Level (1-10)               2030 non-null   float64
 19  Target                             2030 non-null   int64
 20  is_Anxious                         2030 non-null   int64
 21  Therapy History                    203 non-null    str
dtypes: float64(6), int64(8), str(8)
memory usage: 349.0 KB

In [113]:
df.describe()

,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious
count,1968.000000,1994.000000,2030.000000,1936.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,1952.000000,2030.000000,2030.000000,2030.000000
mean,39.921748,6.424624,2.800246,306.275826,9.490148,6.028571,93.066502,20.955665,3.095567,2.359113,5.234119,3.922660,0.103448,0.103448
std,13.243754,2.161544,2.233899,208.012717,6.028653,3.137269,23.313430,5.182524,1.392697,2.148642,2.884946,2.139176,0.304619,0.304619
min,18.000000,-10.000000,-10.000000,0.000000,-10.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,29.000000,5.800000,1.400000,177.750000,5.000000,3.000000,76.000000,17.000000,2.000000,1.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,6.700000,2.800000,277.500000,10.000000,6.000000,93.000000,21.000000,3.000000,2.000000,5.000000,4.000000,0.000000,0.000000
75%,51.000000,7.500000,4.200000,391.000000,15.000000,9.000000,107.000000,26.000000,4.000000,3.000000,8.000000,5.000000,0.000000,0.000000
max,64.000000,11.000000,9.200000,1500.000000,19.000000,15.000000,220.000000,29.000000,5.000000,10.000000,10.000000,10.000000,1.000000,1.000000

In [114]:
df.isnull().sum()
#Age,Gender,sleep,caffeine,smoking,medication,diet,therapy

Age                                    62
Gender                                119
Occupation                              0
Sleep Hours                            36
Physical Activity (hrs/week)            0
Caffeine Intake (mg/day)               94
Alcohol Consumption (drinks/week)       0
Smoking                               106
Family History of Anxiety               0
Stress Level (1-10)                     0
Heart Rate (bpm)                        0
Breathing Rate (breaths/min)            0
Sweating Level (1-5)                    0
Dizziness                               0
Medication                            109
Therapy Sessions (per month)            0
Recent Major Life Event                 0
Diet Quality (1-10)                    78
Anxiety Level (1-10)                    0
Target                                  0
is_Anxious                              0
Therapy History                      1827
dtype: int64

In [115]:
df["Therapy History"].head(50)

0             Group Therapy
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14    Psychodynamic Therapy
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21                      NaN
22                      NaN
23                      NaN
24                      NaN
25                      NaN
26                      NaN
27                      NaN
28                      NaN
29                      NaN
30            Group Therapy
31                      NaN
32    Psychodynamic Therapy
33                      NaN
34                      NaN
35                      NaN
36                      NaN
37                      NaN
38                      NaN
39                      NaN
40                      NaN
41                      NaN
42                      NaN
43                      NaN
44                      NaN
45                      NaN
46                      NaN
47                      NaN
48                      NaN
49                      NaN
Name: Therapy History, dtype: str

In [116]:
columns = {
    "numeric": [
        "Age",
        "Sleep Hours",
        "Physical Activity (hrs/week)",
        "Caffeine Intake (mg/day)",
        "Alcohol Consumption (drinks/week)",
        "Heart Rate (bpm)",
        "Breathing Rate (breaths/min)",
        "Therapy Sessions (per month)"
    ],

    "ordinal": [
        "Stress Level (1-10)",
        "Sweating Level (1-5)",
        "Diet Quality (1-10)",
        "Anxiety Level (1-10)"
    ],

    "categorical": [
        "Gender",
        "Occupation",
        "Smoking",
        "Family History of Anxiety",
        "Dizziness",
        "Medication",
        "Recent Major Life Event",
        "Therapy History"
    ],

    "target": [
        "Target",
        "is_Anxious"
    ]
}

In [117]:
def fix_therapy_history(df):
    df = df.copy()

    
    mask = (df["Therapy Sessions (per month)"] > 0) & (df["Therapy History"].isna())

    df.loc[mask, "Therapy History"] = "Not Reported"

   
    df.loc[df["Therapy Sessions (per month)"] == 0, "Therapy History"] = "No previous history"

    

    return df

In [118]:
def replace_negative_with_nan(df, columns=None):
  

    df = df.copy()

    if columns is None:
        columns = df.select_dtypes(include="number").columns

    for col in columns:
        df.loc[df[col] < 0, col] = np.nan

    return df

In [119]:
def clean_outliers(df, columns=None, multiplier=1.5):
    

    df = df.copy()

    if columns is None:
        columns = df.select_dtypes(include="number").columns

    for col in columns:

        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - multiplier * IQR
        upper = Q3 + multiplier * IQR

        df[col] = df[col].clip(
            lower=lower,
            upper=upper
        )

    return df

In [120]:
def clean_categorical(df, cols):
    df = df.copy()

    for col in cols:

        mode = df[col].mode()

        if not mode.empty:
            df[col] = df[col].fillna(mode[0])

    return df

In [121]:
df=fix_therapy_history(df)
df=replace_negative_with_nan(df)
df=clean_outliers(df)

df=clean_categorical(df,columns["categorical"])

In [122]:
df["Therapy History"].isna().sum()

np.int64(0)

In [123]:
def fillna_numeric(df, cols):
    df = df.copy()

    for col in cols:

        df[col + "_missing"] = df[col].isna().astype(int)

        skew = df[col].skew()

        if abs(skew) < 0.5:
            df[col] = df[col].fillna(df[col].mean())
        else:
            df[col] = df[col].fillna(df[col].median())

    return df

In [124]:
def fillna_ordinal(df, cols):
    df = df.copy()

    for col in cols:

        df[col + "_missing"] = df[col].isna().astype(int)

        df[col] = df[col].fillna(df[col].median())

    return df

In [125]:
df=fillna_numeric(df,columns["numeric"])
df=fillna_ordinal(df,columns["ordinal"])

In [126]:
df["Therapy History"].unique()

<StringArray>
[               'No previous history',                       'Not Reported',
              'Psychodynamic Therapy', 'Cognitive Behavioral Therapy (CBT)',
                      'Group Therapy']
Length: 5, dtype: str

In [127]:
df["Occupation"].unique()

<StringArray>
[   'Teacher',    'Student',     'Lawyer',      'Nurse',      'Other',
   'Musician',   'Engineer',     'Artist',       'Chef',  'Scientist',
    'Athlete', 'Freelancer',     'Doctor']
Length: 13, dtype: str

In [128]:
df.isnull().sum()

Age                                          0
Gender                                       0
Occupation                                   0
Sleep Hours                                  0
Physical Activity (hrs/week)                 0
Caffeine Intake (mg/day)                     0
Alcohol Consumption (drinks/week)            0
Smoking                                      0
Family History of Anxiety                    0
Stress Level (1-10)                          0
Heart Rate (bpm)                             0
Breathing Rate (breaths/min)                 0
Sweating Level (1-5)                         0
Dizziness                                    0
Medication                                   0
Therapy Sessions (per month)                 0
Recent Major Life Event                      0
Diet Quality (1-10)                          0
Anxiety Level (1-10)                         0
Target                                       0
is_Anxious                                   0
Therapy History                              0
Age_missing                                  0
Sleep Hours_missing                          0
Physical Activity (hrs/week)_missing         0
Caffeine Intake (mg/day)_missing             0
Alcohol Consumption (drinks/week)_missing    0
Heart Rate (bpm)_missing                     0
Breathing Rate (breaths/min)_missing         0
Therapy Sessions (per month)_missing         0
Stress Level (1-10)_missing                  0
Sweating Level (1-5)_missing                 0
Diet Quality (1-10)_missing                  0
Anxiety Level (1-10)_missing                 0
dtype: int64

In [129]:
df.isna().sum()

Age                                          0
Gender                                       0
Occupation                                   0
Sleep Hours                                  0
Physical Activity (hrs/week)                 0
Caffeine Intake (mg/day)                     0
Alcohol Consumption (drinks/week)            0
Smoking                                      0
Family History of Anxiety                    0
Stress Level (1-10)                          0
Heart Rate (bpm)                             0
Breathing Rate (breaths/min)                 0
Sweating Level (1-5)                         0
Dizziness                                    0
Medication                                   0
Therapy Sessions (per month)                 0
Recent Major Life Event                      0
Diet Quality (1-10)                          0
Anxiety Level (1-10)                         0
Target                                       0
is_Anxious                                   0
Therapy History                              0
Age_missing                                  0
Sleep Hours_missing                          0
Physical Activity (hrs/week)_missing         0
Caffeine Intake (mg/day)_missing             0
Alcohol Consumption (drinks/week)_missing    0
Heart Rate (bpm)_missing                     0
Breathing Rate (breaths/min)_missing         0
Therapy Sessions (per month)_missing         0
Stress Level (1-10)_missing                  0
Sweating Level (1-5)_missing                 0
Diet Quality (1-10)_missing                  0
Anxiety Level (1-10)_missing                 0
dtype: int64

In [130]:
df["Occupation"].unique()

<StringArray>
[   'Teacher',    'Student',     'Lawyer',      'Nurse',      'Other',
   'Musician',   'Engineer',     'Artist',       'Chef',  'Scientist',
    'Athlete', 'Freelancer',     'Doctor']
Length: 13, dtype: str

In [131]:
df

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Physical Activity (hrs/week)_missing,Caffeine Intake (mg/day)_missing,Alcohol Consumption (drinks/week)_missing,Heart Rate (bpm)_missing,Breathing Rate (breaths/min)_missing,Therapy Sessions (per month)_missing,Stress Level (1-10)_missing,Sweating Level (1-5)_missing,Diet Quality (1-10)_missing,Anxiety Level (1-10)_missing
0,59.0,Other,Teacher,7.0,2.4,40.0,5.000000,Yes,No,4.0,...,0,0,0,0,0,0,0,0,0,0
1,46.0,Female,Student,5.1,5.4,156.0,11.000000,Yes,No,3.0,...,0,0,0,0,0,0,0,0,0,0
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.000000,Yes,Yes,9.0,...,0,0,0,0,0,0,0,0,0,0
3,40.0,Male,Nurse,7.6,0.9,129.0,0.000000,No,No,9.0,...,0,0,0,0,0,0,0,0,0,0
4,26.0,Male,Other,6.7,3.0,64.0,13.000000,No,No,15.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,42.0,Male,Teacher,3.7,2.9,113.0,18.000000,Yes,Yes,4.0,...,0,0,0,0,0,0,0,0,0,0
2026,34.0,Other,Freelancer,8.4,2.0,239.0,14.000000,No,No,7.0,...,0,0,0,0,0,0,0,0,0,0
2027,62.0,Female,Musician,6.1,1.6,149.0,18.000000,Yes,No,2.0,...,0,0,0,0,0,0,0,0,0,0
2028,47.0,Other,Nurse,6.3,1.1,298.0,9.786432,No,Yes,7.0,...,0,0,1,0,0,0,0,0,0,0
2029,44.0,Female,Engineer,6.0,7.9,268.0,3.000000,No,Yes,7.0,...,0,0,0,0,0,0,0,0,0,0

In [132]:
def bining_features(df):
    df = df.copy()

    bin_config = {

        "Age": (
            [0, 18, 30, 50, 120],
            ["Teen", "Young Adult", "Adult", "Senior"]
        ),

        "Sleep Hours": (
            [0, 5, 7, 9, 24],
            ["Sleep Deprived", "Normal Sleep", "Healthy Sleep", "Oversleeping"]
        ),

        "Physical Activity (hrs/week)": (
            [-1, 2, 5, 100],
            ["Non-Athletic", "Moderately Active", "Athletic"]
        ),

        "Caffeine Intake (mg/day)": (
            [-1, 100, 300, 600, 2000],
            ["Low", "Moderate", "High", "Coffee Addict"]
        ),

        "Alcohol Consumption (drinks/week)": (
            [-1, 0, 5, 10, 100],
            ["None", "Light", "Moderate", "Heavy"]
        ),

        "Heart Rate (bpm)": (
            [0, 60, 100, 200],
            ["Low", "Normal", "High"]
        ),

        "Breathing Rate (breaths/min)": (
            [0, 12, 20, 100],
            ["Slow", "Normal", "Rapid"]
        ),

        "Therapy Sessions (per month)": (
            [-1, 0, 2, 5, 20],
            ["No Therapy", "Occasional", "Regular", "Intensive"]
        ),

        "Stress Level (1-10)": (
            [0, 3, 6, 10],
            ["Low Stress", "Moderate Stress", "High Stress"]
        ),

        "Diet Quality (1-10)": (
            [0, 3, 6, 8, 10],
            ["Unhealthy", "Average", "Healthy", "Excellent"]
        ),

        "Anxiety Level (1-10)": (
            [0, 3, 6, 10],
            ["Low Anxiety", "Moderate Anxiety", "High Anxiety"]
        )

    }

    for col in bin_config:

        bins, labels = bin_config[col]
        df[f"Binned_{col}"] = pd.cut(
            df[col],
            bins=bins,
            labels=labels
            )

       
    return df

In [133]:
df=bining_features(df)

In [134]:
def reclassify_categorical(data, col, mapping, new_col=None):
    """
    Reclassify categories of a categorical column.

    Parameters:
    ----------
    data : pd.DataFrame
        Input dataset.
    col : str
        Column name to reclassify.
    mapping : dict
        Dictionary mapping old categories to new categories.
        Example: {"Bachelor": "HigherEdu", "Master": "HigherEdu", "PhD": "HigherEdu"}
    new_col : str, optional
        Name of new column. If None, overwrites the original column.

    Returns:
    -------
    pd.DataFrame
        DataFrame with reclassified column.
    """
    if new_col is None:
        new_col = col
    
    data[new_col] = data[col].replace(mapping)
    return data

In [135]:
occupation_map = {
    "Teacher": "Academic",
    "Student": "Academic",
    "Scientist": "Academic",

    "Doctor": "Healthcare",
    "Nurse": "Healthcare",

    "Engineer": "Technical",

    "Artist": "Creative",
    "Musician": "Creative",
    "Chef": "Creative",

    "Lawyer": "Professional",
    "Athlete": "Professional",

    "Freelancer": "Other"
   
}

df = reclassify_categorical(df, "Occupation", occupation_map, new_col="Occupation_Group")

In [136]:
therapy_map = {
    "Psychodynamic Therapy": "Therapy",
    "Cognitive Behavioral Therapy (CBT)": "Therapy",
    "Group Therapy": "Therapy",
    "No previous history": "No Therapy",
    "Not Reported": "Therapy"
    
}

df = reclassify_categorical(df, "Therapy History", therapy_map, new_col="Therapy_Group")

In [137]:
df

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Binned_Caffeine Intake (mg/day),Binned_Alcohol Consumption (drinks/week),Binned_Heart Rate (bpm),Binned_Breathing Rate (breaths/min),Binned_Therapy Sessions (per month),Binned_Stress Level (1-10),Binned_Diet Quality (1-10),Binned_Anxiety Level (1-10),Occupation_Group,Therapy_Group
0,59.0,Other,Teacher,7.0,2.4,40.0,5.000000,Yes,No,4.0,...,Low,Light,Normal,Rapid,No Therapy,Moderate Stress,Unhealthy,Low Anxiety,Academic,No Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11.000000,Yes,No,3.0,...,Moderate,Heavy,Normal,Normal,Occasional,Low Stress,Unhealthy,Moderate Anxiety,Academic,Therapy
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.000000,Yes,Yes,9.0,...,High,Heavy,High,Rapid,Intensive,High Stress,Average,High Anxiety,Professional,Therapy
3,40.0,Male,Nurse,7.6,0.9,129.0,0.000000,No,No,9.0,...,Moderate,None,High,Normal,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
4,26.0,Male,Other,6.7,3.0,64.0,13.000000,No,No,15.0,...,Low,Heavy,High,Normal,No Therapy,NaN,Average,Low Anxiety,Other,No Therapy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,42.0,Male,Teacher,3.7,2.9,113.0,18.000000,Yes,Yes,4.0,...,Moderate,Heavy,Normal,Normal,Occasional,Moderate Stress,Unhealthy,Low Anxiety,Academic,Therapy
2026,34.0,Other,Freelancer,8.4,2.0,239.0,14.000000,No,No,7.0,...,Moderate,Heavy,Normal,Normal,No Therapy,High Stress,Average,Moderate Anxiety,Other,No Therapy
2027,62.0,Female,Musician,6.1,1.6,149.0,18.000000,Yes,No,2.0,...,Moderate,Heavy,Normal,Rapid,Regular,Low Stress,Healthy,Low Anxiety,Creative,Therapy
2028,47.0,Other,Nurse,6.3,1.1,298.0,9.786432,No,Yes,7.0,...,Moderate,Moderate,Normal,Rapid,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
2029,44.0,Female,Engineer,6.0,7.9,268.0,3.000000,No,Yes,7.0,...,Moderate,Light,Normal,Rapid,Regular,High Stress,Average,Moderate Anxiety,Technical,Therapy

In [138]:
df

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Binned_Caffeine Intake (mg/day),Binned_Alcohol Consumption (drinks/week),Binned_Heart Rate (bpm),Binned_Breathing Rate (breaths/min),Binned_Therapy Sessions (per month),Binned_Stress Level (1-10),Binned_Diet Quality (1-10),Binned_Anxiety Level (1-10),Occupation_Group,Therapy_Group
0,59.0,Other,Teacher,7.0,2.4,40.0,5.000000,Yes,No,4.0,...,Low,Light,Normal,Rapid,No Therapy,Moderate Stress,Unhealthy,Low Anxiety,Academic,No Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11.000000,Yes,No,3.0,...,Moderate,Heavy,Normal,Normal,Occasional,Low Stress,Unhealthy,Moderate Anxiety,Academic,Therapy
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.000000,Yes,Yes,9.0,...,High,Heavy,High,Rapid,Intensive,High Stress,Average,High Anxiety,Professional,Therapy
3,40.0,Male,Nurse,7.6,0.9,129.0,0.000000,No,No,9.0,...,Moderate,None,High,Normal,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
4,26.0,Male,Other,6.7,3.0,64.0,13.000000,No,No,15.0,...,Low,Heavy,High,Normal,No Therapy,NaN,Average,Low Anxiety,Other,No Therapy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,42.0,Male,Teacher,3.7,2.9,113.0,18.000000,Yes,Yes,4.0,...,Moderate,Heavy,Normal,Normal,Occasional,Moderate Stress,Unhealthy,Low Anxiety,Academic,Therapy
2026,34.0,Other,Freelancer,8.4,2.0,239.0,14.000000,No,No,7.0,...,Moderate,Heavy,Normal,Normal,No Therapy,High Stress,Average,Moderate Anxiety,Other,No Therapy
2027,62.0,Female,Musician,6.1,1.6,149.0,18.000000,Yes,No,2.0,...,Moderate,Heavy,Normal,Rapid,Regular,Low Stress,Healthy,Low Anxiety,Creative,Therapy
2028,47.0,Other,Nurse,6.3,1.1,298.0,9.786432,No,Yes,7.0,...,Moderate,Moderate,Normal,Rapid,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
2029,44.0,Female,Engineer,6.0,7.9,268.0,3.000000,No,Yes,7.0,...,Moderate,Light,Normal,Rapid,Regular,High Stress,Average,Moderate Anxiety,Technical,Therapy

In [139]:
df.to_csv("cleaned_data.csv", index=False)

In [140]:
data=pd.read_csv("cleaned_data.csv")

In [141]:
data

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Binned_Caffeine Intake (mg/day),Binned_Alcohol Consumption (drinks/week),Binned_Heart Rate (bpm),Binned_Breathing Rate (breaths/min),Binned_Therapy Sessions (per month),Binned_Stress Level (1-10),Binned_Diet Quality (1-10),Binned_Anxiety Level (1-10),Occupation_Group,Therapy_Group
0,59.0,Other,Teacher,7.0,2.4,40.0,5.000000,Yes,No,4.0,...,Low,Light,Normal,Rapid,No Therapy,Moderate Stress,Unhealthy,Low Anxiety,Academic,No Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11.000000,Yes,No,3.0,...,Moderate,Heavy,Normal,Normal,Occasional,Low Stress,Unhealthy,Moderate Anxiety,Academic,Therapy
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.000000,Yes,Yes,9.0,...,High,Heavy,High,Rapid,Intensive,High Stress,Average,High Anxiety,Professional,Therapy
3,40.0,Male,Nurse,7.6,0.9,129.0,0.000000,No,No,9.0,...,Moderate,NaN,High,Normal,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
4,26.0,Male,Other,6.7,3.0,64.0,13.000000,No,No,15.0,...,Low,Heavy,High,Normal,No Therapy,NaN,Average,Low Anxiety,Other,No Therapy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,42.0,Male,Teacher,3.7,2.9,113.0,18.000000,Yes,Yes,4.0,...,Moderate,Heavy,Normal,Normal,Occasional,Moderate Stress,Unhealthy,Low Anxiety,Academic,Therapy
2026,34.0,Other,Freelancer,8.4,2.0,239.0,14.000000,No,No,7.0,...,Moderate,Heavy,Normal,Normal,No Therapy,High Stress,Average,Moderate Anxiety,Other,No Therapy
2027,62.0,Female,Musician,6.1,1.6,149.0,18.000000,Yes,No,2.0,...,Moderate,Heavy,Normal,Rapid,Regular,Low Stress,Healthy,Low Anxiety,Creative,Therapy
2028,47.0,Other,Nurse,6.3,1.1,298.0,9.786432,No,Yes,7.0,...,Moderate,Moderate,Normal,Rapid,Occasional,High Stress,Unhealthy,Moderate Anxiety,Healthcare,Therapy
2029,44.0,Female,Engineer,6.0,7.9,268.0,3.000000,No,Yes,7.0,...,Moderate,Light,Normal,Rapid,Regular,High Stress,Average,Moderate Anxiety,Technical,Therapy